language: php
 
php:
  - 5.5
  - 5.6
  - 7.1
 
before_script:
  - composer self-update
  - composer install --no-interaction --dev

script: phpunit

notifications:
    on_success: never
    on_failure: always
